// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU6IZzPZBecHCoTKMs2WtxOaWmZQzE4c8',
    appId: '1:633269520452:web:d08f58a3a42eb3d7b29411',
    messagingSenderId: '633269520452',
    projectId: 'cars-84828',
    authDomain: 'cars-84828.firebaseapp.com',
    storageBucket: 'cars-84828.appspot.com',
    measurementId: 'G-7J85PM238H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwelkp0JQGZb80UpsU2tms07UqG-ZiI1E',
    appId: '1:633269520452:android:c77fa82054f9e6d5b29411',
    messagingSenderId: '633269520452',
    projectId: 'cars-84828',
    storageBucket: 'cars-84828.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASg1ia06hQjT_M2vS6XQOQUKaCZOTSFkY',
    appId: '1:633269520452:ios:2448694a70a12af0b29411',
    messagingSenderId: '633269520452',
    projectId: 'cars-84828',
    storageBucket: 'cars-84828.appspot.com',
    iosClientId: '633269520452-5ak0vhlkstsb749s3e3c88lis44j7449.apps.googleusercontent.com',
    iosBundleId: 'com.example.car',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASg1ia06hQjT_M2vS6XQOQUKaCZOTSFkY',
    appId: '1:633269520452:ios:da6c42a247bf937db29411',
    messagingSenderId: '633269520452',
    projectId: 'cars-84828',
    storageBucket: 'cars-84828.appspot.com',
    iosClientId: '633269520452-vrcg6omf58p6f4ptob14pgd04gp4k63n.apps.googleusercontent.com',
    iosBundleId: 'com.example.car.RunnerTests',
  );
}
